### ISSUE TITLE
Travail pour le 4 : utilisation de Outil > Afficher les erreurs pour le document actuel

### ISSUE THREAD

**Issue by brandelune** [brandelune/omegat-internship#1]
Bonjour @AlexandraAnselmi57 
La première journée a été un peu dense, je pense. On va y aller plus tranquillement à partir d’aujourd’hui.

Ce matin j’ai revu les quelques modifications d’hier, j’ai fait d’autres modifications, et j’ai mis des notes dans certains segments. Pour les consulter, utiliser le menu Atteindre > Note suivante

Aujourd’hui on va travailler avec l’outil de correction des erreurs. Outils > Afficher les erreurs pour le document actuel
L’outil n’est pas difficile à utiliser, il vous présente les erreurs qu’OmegaT pense avoir détectées dans un fichier donné. Vous pouvez naviguer dans la liste cliquer sur un segment pour passer dans l’éditeur et corriger, etc.
Il va y avoir des erreurs qui n’en sont pas. Les règles de vérifications sont assez strictes donc il y a beaucoup de « faux positifs ». C’est à vous de corriger ce qui est nécessaire.

Pour aujourd’hui on va travailler de la manière suivante :
1. vous allez choisir un fichier dans la liste des fichiers du projet
2. cliquez dessus pour l’afficher dans l’interface
3. cliquez sur Outils > Afficher les erreurs pour le document actuel
4. OmegaT vous affiche des segments erronés, vérifiez-les dans l’interface de lecture des erreurs

Les erreurs « Terminologiques » viennent des termes enregistrés dans le glossaire.

**Comment by AlexandraAnselmi57** [comment]
Bilan Activité 4 mai : Correction des erreurs dans « afficher les erreurs pour le document actuel », erreurs pour Bundle.properties

**Comment by brandelune** [comment]
Bilan Activité 3 mai: modifier les nomenclatures "Source", modification dans "recherche exacte", filtration des segments
