### ISSUE TITLE
Travail pour le 13 mai: valider les propositions du 12, continuation de la vérification du manuel

### ISSUE THREAD

**Issue by brandelune** [brandelune/omegat-internship#10]
Bonjour @AlexandraAnselmi57 

Vous avez bien travaillé hier. Merci. On avance bien. Pour aujourd'hui:
- Fermer le ticket d'hier et mettre le lien (attention à l'adresse du lien) dans le bilan global
- lecture/notes/modifications des pages 20-26 (jusqu'à avant "4. Remplacement de texte")

**Comment by AlexandraAnselmi57** [comment]
Bilan Activité 13 mai : Correction des notes de la veille, lecture des pages 20 à 26, prise de notes, correction des pages 20 à 26 dans les notes et segments sur OmegaT, ajout de segments à modifier dans le manuel anglais dans "Modifications à apporter éventuellement au manuel anglais".

**Comment by brandelune** [comment]
Parfait. N'oubliez pas de fermer le ticket et de l'inscrire au bilan de la semaine quand vous avez fini votre journée.
