### ISSUE TITLE
Travail pour le 14 mai: valider les commentaires du 13, continuation de la vérification du manuel

### ISSUE THREAD

**Issue by brandelune** [brandelune/omegat-internship#11]
Bonjour @AlexandraAnselmi57

Aujourd'hui on ne va pas enregistrer de modifications dans OmegaT, seulement des notes.

- Fermer le ticket d'hier et mettre le lien (attention à l'adresse du lien) dans le bilan global
- lecture/notes des pages 26-32 (jusqu'à avant "Fichiers HTML et XHTML")

**Comment by brandelune** [comment]
Désolé de ne pas avoir pu vous voir aujourd'hui. On se retrouve lundi !
Pas de soucis, à lundi !

**Comment by AlexandraAnselmi57** [comment]
Bilan Activité 14 mai : Correction des notes de la veille, ajouts de segments à modifier dans le ticket  « Modifications à apporter éventuellement au manuel anglais » et dans le ticket « Modifications à éventuellement apporter ailleurs qu'au manuel anglais », lecture des pages 26 à 32, prise de notes, correction dans les notes sur OmegaT.
