### ISSUE TITLE
Travail pour le 17 mai: mettre à jour la page de garde, vérifier les retours sur les notes et travailler sur les pages 32-37

### ISSUE THREAD

**Issue by brandelune** [brandelune/omegat-internship#12]
Bonjour @AlexandraAnselmi57 

Aujourd'hui vous allez vous-même mettre à jour la page de garde en étudiant sa syntaxe et en recopiant/modifiant les parties nécessaires pour créer la section de cette nouvelle semaine.

Ensuite, vous allez passer dans les notes pour voir les actions à faire.

Et vous continuerez sur les pages 32 à 37 du manuel, jusqu'à "7.12. Éditeur".

Attention à vous focaliser sur le manuel dans OmegaT, j'ai vu que vous aviez annoté des fichiers qui ne font pas partie de celui-ci. La démarche est donc: lecture du PDF, prise de notes dans le PDF (papier) pendant la lecture, recherche des segments concernés dans OmegaT et annotation/modification des segments correspondants.

**Comment by AlexandraAnselmi57** [comment]
Bilan Activité 17 mai : Modification de la page de garde sur GitHub, correction des notes de vendredi, ajouts de segments à modifier dans le ticket  « Modifications à apporter éventuellement au manuel anglais », lecture des pages 32 à 37, prise de notes, correction des pages 32 à 37 dans les notes et segments sur OmegaT.
