### ISSUE TITLE
Travail pour le 18 mai : bouclage des notes de la veille, avancée sur la lecture du PDF

### ISSUE THREAD

**Issue by brandelune** [brandelune/omegat-internship#13]
Bonjour @AlexandraAnselmi57 

- Modification de la page de garde, fermeture du ticket d'hier
- Pour les notes d'hier, faites les actions nécessaires.
- Aujourd'hui on va essayer de boucler le PDF jusqu'au début de la page 44 (avant 2. Correspondances).

**Comment by AlexandraAnselmi57** [comment]
Bilan Activité 18 mai : Correction des notes de la veille, ajouts de segments à modifier dans le ticket  « Modifications à apporter éventuellement au manuel anglais » et modification dans le ticket « Modifications à éventuellement apporter ailleurs qu'au manuel anglais », lectures des pages 38 à 44, prise de notes, correction dans les notes et segments sur OmegaT.
