### ISSUE TITLE
Travail pour le 19 mai : bouclage des notes de la veille, avancée sur la lecture du PDF

### ISSUE THREAD

**Issue by brandelune** [brandelune/omegat-internship#14]
Bonjour @AlexandraAnselmi57 

Pour aujourd'hui, un peu de routine
- Modifier la page de garde
- Traiter les notes. Il y en a beaucoup à effacer car elles ont été traitées. Il est préférable d'effacer une note plutôt que de m'écrire "Ok".
- Je vais vous expliquer le problème du "below" des dossiers
- Et vous allez travailler sur le PDF jusqu'à la page 49, et on est largement dans les temps !

**Comment by AlexandraAnselmi57** [comment]
Bilan Activité 19 mai : Correction des notes de la veille, ajouts de segments à modifier dans le ticket  « Modifications à apporter éventuellement au manuel anglais », lecture des pages 45 à 49, prise de notes, correction dans les notes et segments sur OmegaT.
