### ISSUE TITLE
Travail pour le 20 mai : bouclage des notes de la veille, avancée sur la lecture du PDF...

### ISSUE THREAD

**Issue by brandelune** [brandelune/omegat-internship#15]
Bonjour @AlexandraAnselmi57 

Content de voir qu'on commence à avoir une routine.
Merci pour les commentaires, j'en ai rajouté, à vous de voir comment traiter les segments.

Pour le manuel, on va essayer d'aller jusqu'à la page 55 aujourd'hui.

**Comment by AlexandraAnselmi57** [comment]
Bilan Activité 20 mai : Correction des notes de la veille, ajouts de segments à modifier dans le ticket  « Modifications à apporter éventuellement au manuel anglais », lecture des pages 50 à 55, prise de notes, correction dans les notes et segments sur OmegaT.
