### ISSUE TITLE
Travail pour le 21 mai : gestion des notes, reprise de l'installation XMLmind, avancée sur la lecture

### ISSUE THREAD

**Issue by brandelune** [brandelune/omegat-internship#16]
Bonjour @AlexandraAnselmi57 

Aujourd'hui on va continuer l'installation de XMLmind pour voir comment les choses se passent dans le manuel, et on va également tenter de créer la nouvelle version d'OmegaT.

En plus de ça, on va continuer sur les notes qui restent et sur la lecture, si possible jusqu'à la page 60. À partir de la page 61 on rentre dans les annexes et on bouclera ça dans les 3 premiers jours de la semaine prochaine.

**Comment by AlexandraAnselmi57** [comment]
Bilan activité 21 mai : : Correction des notes de la veille, ajouts de segments à modifier dans le ticket  « Modifications à apporter éventuellement au manuel anglais » et dans le ticket « Modifications à éventuellement apporter ailleurs qu'au manuel anglais », lectures des pages 56 à 60, prise de notes, correction dans les notes et segments sur OmegaT.

**Comment by brandelune** [comment]
Désolé de ne pas avoir pu conclure sur XMLmind et sur le code. On fait ça lundi.
