### ISSUE TITLE
Travail pour le 24 mai : gestion des notes, manuel p.62-68

### ISSUE THREAD

**Issue by brandelune** [brandelune/omegat-internship#17]
Bonjour @AlexandraAnselmi57 

J'espère que vous avez passé un bon week-end.
Cette semaine on va se focaliser sur la fin de la correction du manuel, et on utilisera les derniers jours du mois pour préparer le mois de juin avec @vbdx et pour éventuellement jeter un coup d’œil sur le site web. Dans cet esprit, on va donc commencer la semaine un peu comme les autre jours:

- mise à jour de la page de garde pour rentrer dans la nouvelle semaine
- gestion des notes passées et éventuellement ajout de commentaires dans les tickets "corrections externes au français"
- lecture/correction des pages 62-68 du manuel (j'attache la toute dernière version qui contient vos modifications)

Et en plus on va tenter conclure l'installation de XMLMind (xxe), et voir comment les fichiers "source" sont réellement structurés.

Dans la semaine on essayera de construire la dernière version d'OmegaT à partir du code cloné (juste pour s'amuser), on essayera de faire des modifications sur le manuel anglais pour se familiariser avec la procédure qui est un peu complexe. Je vous rappelle que le code que vous avez sur votre machine est "cloné" et donc "lié" organiquement à ce qui se trouve sur le serveur Github. On verra que la procédure est un peu plus complexe que juste "enregistrer" une modification.

**Comment by brandelune** [comment]
[OmegaT_documentation_fr_0524.PDF](https://github.com/brandelune/omegat-internship/files/6531017/OmegaT_documentation_fr_0524.PDF)

**Comment by AlexandraAnselmi57** [comment]
Bilan Activité 24 mai : Correction des notes de la veille, ajouts de segments à modifier dans le ticket  « Modifications à apporter éventuellement au manuel anglais »,lectures des pages 61 à 68, prise de notes, correction dans les notes et segments sur OmegaT.
