### ISSUE TITLE
Travail pour le 25 mai : gestion des notes, manuel p. 69-73

### ISSUE THREAD

**Issue by brandelune** [brandelune/omegat-internship#18]
Bonjour @AlexandraAnselmi57 

On continue aujourd'hui vers la fin du manuel. Si tout se passe bien on aura fini la relecture et la prise en charge de vos modifications jeudi. Même routine aujourd'hui donc, avec mes excuses.

- modification de la page de garde
- gestion des notes
- avancée sur la lecture (p. 69-73)

**Comment by AlexandraAnselmi57** [comment]
Bilan Activité 25 mai : Correction des notes de la veille, ajouts de segments à modifier dans le ticket  « Modifications à apporter éventuellement au manuel anglais », lectures des pages 69 à 71, prise de notes, correction dans les notes et segments sur OmegaT.
