### ISSUE TITLE
Travail pour le 26 mai : gestion des notes, manuel p. 72-77

### ISSUE THREAD

**Issue by brandelune** [brandelune/omegat-internship#19]
Bonjour @AlexandraAnselmi57 

Et hop ! On arrive à la fin du manuel. Dernier jour de routine...

- Gestion des notes (il n'y en a que 2 si je ne me trompe pas)
- Correction des pages restantes.

**Comment by AlexandraAnselmi57** [comment]
Bilan Activité 26 mai : Correction des notes de la veille, ajouts de segments à modifier dans le ticket  « Modifications à apporter éventuellement au manuel anglais »,lectures des pages 72 à 77, prise de notes, correction dans les notes sur OmegaT.
