### ISSUE TITLE
Travail pour le 5, continuation des corrections, utilisation des Notes

### ISSUE THREAD

**Issue by brandelune** [brandelune/omegat-internship#2]
Bonjour @AlexandraAnselmi57 
On se retrouve à 18h, heure de Tokyo, et en attendant je vous demande de continuer la vérification comme vous l'avez commencée hier.

Cependant, ma vérification de vos modifications hier m'amène à vous suggérer ceci:
- méfiez-vous des suggestions, les majuscules en tête de segment ne sont pas toujours nécessaires
- il serait préférable dans un premier temps que vous n'effectuiez pas les modifications directement mais que vous inscriviez votre modification dans le panneau "Notes" pour que je puisse voir l'original et ce que vous proposez.

Je vous retrouve d'ici 4h !

**Comment by brandelune** [comment]
Ça y est, je vous ai envoyé le PDF. Je vous conseille de l'imprimer et de le lire séparément. Essayez de traiter 4-5 pages par jour. Vous allez remarquer des problèmes de typographie (espace absente, etc.) et bien sûr des problèmes de grammaire et d'orthographe. Faites une recherche sur la partie fautive dans OmegaT et corrigez directement.

N'oubliez pas de mettre un ? dans les Notes de segments dont la signification vous échappe.

**Comment by AlexandraAnselmi57** [comment]
Bilan Activité 5 mai : Correction des segments du PDF OmegaT_documentation_fr_0505, recherche sur la partie fautive dans OmegaT, correction dans les Notes de segments
