### ISSUE TITLE
Travail pour les 27 et 28 mai : un peu de repos et début du rapport

### ISSUE THREAD

**Issue by brandelune** [brandelune/omegat-internship#20]
Bonjour @AlexandraAnselmi57,

- J'ai commenté les quelques notes qui restent, à vous de les traiter.
- Sur la page de garde, ajoutez dans les tâches à accomplir la correction jusqu'à la dernière page et la rédaction d'un bilan du mois
- Au sujet de ce bilan, notez ce que vous avez appris et ce qui vous a paru difficile, et au sujet du manuel, ce qui vous a paru difficile à comprendre

**Comment by AlexandraAnselmi57** [comment]
Bilan Activité 27 et 28 mai : Correction des notes du 26 mai, ajouts de segments à modifier dans le ticket  « Modifications à apporter éventuellement au manuel anglais », rédaction d'un bilan du mois de mai.
