### ISSUE TITLE
Travail pour le 1 er juin : préparation de l'environnement pour travailler sur les sources DocBook, unification des références à Mac en macOS (Mac, Mac OSX, OSX, OS X, etc...) 

### ISSUE THREAD

**Issue by AlexandraAnselmi57** [brandelune/omegat-internship#22]

**Comment by brandelune** [comment]
On va travailler sur le contenu du premier commentaire:
https://github.com/brandelune/omegat-internship/issues/5#issuecomment-834289612

**Comment by AlexandraAnselmi57** [comment]
Bilan Activité 1 er juin : Travail sur l'environnement pour travailler sur les sources DocBook du manuel. On s’est assurés que les outils Git Bash et XML Mind sur Windows sont utilisables et on a commencé à établir un protocole pour modifier les fichiers source,
