### ISSUE TITLE
Travail pour le 6, continuation de la correction à partir du PDF

### ISSUE THREAD

**Issue by brandelune** [brandelune/omegat-internship#3]
Bonjour @AlexandraAnselmi57 

Vous avez fait du très bon travail hier.

J'ai modifié mon interface de travail pour voir la traduction de "référence" (celle qui existait avant que vous travailliez sur le projet) et vos notes.

<img width="696" alt="Screen Shot 2021-05-06 at 9 36 17" src="https://user-images.githubusercontent.com/28946328/117226208-1dc48580-ae4f-11eb-9b2a-adfb3a6a10b7.png">

J'ai écrit des réponse pour toutes (?) vos notes. Allez les visiter en utilisant Atteindre > Note suivante

Nous allons donc continuer de la manière suivante:
- vous corrigez directement dans OmegaT
- vous rajoutez une note quand vous avez un questionnement

dans un premier temps, privilégiez le questionnement, si vous n'êtes pas sûre, passez-moi la main, je vous réponds et vous corrigez ensuite.

Aujourd'hui vous allez donc commencer par vérifier mes réponses, éventuellement faire les modifications nécessaires dans le segment. Pour toutes les notes, répondez avec un OK pour que je voie bien que vous avez vu ma réponse et que vous avez agit en conséquence.

Une fois cette vérification faite, vous repassez dans le PDF, relisez, corrigez dans OmegaT, mettez des notes, etc.

Et on se retrouve à 18h.

**Comment by AlexandraAnselmi57** [comment]
Bilan Activité 6 mai : Vérification des réponses des notes, correction des notes, relecture du PDF, correction des segments du PDF  dans OmegaT (ainsi que dans quelques notes).

**Comment by brandelune** [comment]
C'est parfait. J'ai rajouté quelques commentaires et actions.
Pour les choses à noter au sujet de la version anglaise, je vais créer 2 tickets, un pour le manuel anglais et un pour les problèmes à gérer ailleurs (par ex, modifier la source).
