### ISSUE TITLE
Travail pour le 7 mai. Lecture du PDF imprimé, prise de notes, corrections directes avec commentaires

### ISSUE THREAD

**Issue by brandelune** [brandelune/omegat-internship#4]
Bonjour @AlexandraAnselmi57 
On commence à prendre un bon rythme.

Aujourd'hui vous allez tenter de faire ceci:
1. faire le bilan de mes réponses d'hier (actions, commentaires, etc.)
2. commencer à travailler avec le PDF imprimé

J'Imagine que vous avec le PDF imprimé aujourd'hui. Vous allez commencer par le lire, disons jusqu'au début de la page 6, avant "7. Démarrage d'OmegaT à partir d'une ligne de commande".

Au fur et à mesure de la lecture vous allez prendre des notes sur
- ce que vous ne comprenez pas
- ce qui /est/ incorrect
- ce qui /semble/ incorrect

Une fois que vous avez bouclé la lecture et la prise de notes, passez dans OmegaT, cherchez les segments problématiques et ajoutez des commentaires, effectuez les modifications, etc. comme on a fait jusqu'à présent.

Je vais créer 2 tickets supplémentaires. Un pour les modifications à éventuellement effectuer dans le manuel en anglais et un pour les autres modifications. On remplira ces tickets au fur et à mesure, pour préparer le mois de juin.

Bonne journée !

**Comment by AlexandraAnselmi57** [comment]
Bilan Activité 7 mai : Bilan des commentaires et des actions de la veille, lecture des six premières pages du PDF, prise de notes, correction des segments problématiques du PDF dans OmégaT, correction des notes de la veille, ajouts de modifications à apporter au manuel anglais et ailleurs qu’au manuel anglais dans le dépôt « Internship ».

**Comment by brandelune** [comment]
Ok, parfait. On continue comme ça lundi !

Pourriez-vous ajouter ce ticket dans le bilan de la semaine comme je l'ai fait pour les autres jours ?
Quand vous avez fini, merci de fermer ce ticket en appuyant sur "Close issue" en bas à droite ici.
