### ISSUE TITLE
Travail pour le 10 mai :  validation de toutes les notes qui restent, action, continuation de la relecture sur PDF/papier

### ISSUE THREAD

**Issue by brandelune** [brandelune/omegat-internship#7]
Bonjour @AlexandraAnselmi57 
J'espère que vous allez passer un bon week-end.

J'ai fait le tour de toutes les notes encore enregistrées dans le projet. J'ai mis des réponses à certaines, j'en ai effacé certaines (l'action sur le segment a été validée), etc.

Votre première tâche lundi sera de passer une fois sur toutes les notes qui restent de la première semaine et d'en faire une validation finale si possible. Si elles sont bouclés (plus de questions, etc.), vous les effacez. S'il reste des doutes, vous rajoutez un commentaire.

La seconde partie de la lecture portera sur les pages 6 à 11, donc juste avant de passer à la description des menus.

On continue à travailler comme on a fait: vous relisez sur papier, vous prenez des notes, vous cherchez les segments problématiques dans OmegaT, vous ajoutez une note avec ou pas de modification dans le segment.

**Comment by AlexandraAnselmi57** [comment]
Bilan Activité 10 mai : Correction des notes, lecture des pages 6 à 11 du PDF, prise de notes, correction dans les segments et les notes sur OmegaT.
