### ISSUE TITLE
Travail pour le 11 mai :  tests pour identifier le problème à l'ouverture du projet, reprise des saisies d'hier, avancée sur le manuel

### ISSUE THREAD

**Issue by brandelune** [brandelune/omegat-internship#8]
Bonjour @AlexandraAnselmi57,

J'ai eu le même probleme qu'il y a quelques jours avec le projet OmegaT.
Quand je l'ai ouvert ce matin, il n'y avait que quelques dizaines de segments traduits et j'ai été obligé de remettre le projet en l'état à partir de la mémoire du 8 mai, donc votre travail de lundi a été annulé.

C'est étrange. Et j'ai l'impression que ça a peut-être à voir avec la manière dont vous fermez le projet en fin de journée. Il va falloir faire des tests pour identifier le problème.

On fera ça lors de notre bilan quotidien.

Pour votre début de journée, je vous propose donc les tâches suivantes:
1) inscrire le ticket du 10 mai dans le bilan de la 2e semaine (page de garde de ce dépôt) et le fermer
2) reprendre les saisies que vous avez effectuées hier
3) avancer sur le manuel, si possible de la page 12 à la page 16 (jusqu'à avant "5. Outils")
4) effectuer les tests pour identifier le problème de perte des données à l'ouverture.

**Comment by AlexandraAnselmi57** [comment]
Bilan Activité 11 mai : Explications sur la récupération et sur l'enregistrement des modifications, Récupération des modifications de la veille perdues, lecture des pages 12 à 16 du PDF, petit bilan sur la récupération et l’enregistrement des modifications sur OmegaT, reprise de la correction de quelques segments de la veille.

**Comment by AlexandraAnselmi57** [comment]
Petit bilan sur la récupération et l’enregistrement des modifications sur OmegaT :
OmegaT enregistre localement automatiquement les données de nos modifications, toutes les 3 minutes.
Il place ces données sur le serveur à chaque synchronisation.
Les synchronisations ont lieu:
- quand on enregistres les modifications manuellement
- quand on crée les fichiers cible
- quand on recharge le projet
- quand on ferme le projet
- environ toutes les 10 minutes (à vérifier)
Donc, lorsque plusieurs personnes travaillent sur un même projet, la synchronisation ne se fera pas en même temps.
Les données des modifications (mémoire de traduction "project_save.tmx, et glossaire principal) sont enregistrées à l'intérieur des fichiers qui constituent le projet. Ces fichiers sont stockés localement dans l'ordinateur et OmegaT nous en montre le contenu textuel.

Hier, nos modifications ont disparu d’OmegaT. Et nous nous sommes rendus compte qu'effectivement, le fichier de mémoire principal qui devait faire 3 mo, ne faisait plus que quelques ko. Mais, heureusement, les données étaient partiellement présentes dans un fichier de sauvegarde présent localement, ce qui nous permet de les récupérer.

Dans Windows, chaque dossier peut être classé par date et grâce à la date, nous avons pu retrouver le dernier fichier correctement enregistré. Il a fallu ensuite déposer ce fichier dans le dossier /tm/enforce du projet OmegaT, pour revoir apparaître les modifications qui avaient disparu. Nous avons pu ainsi récupérer une partie de mon travail.

**Comment by brandelune** [comment]
Merci pour ce bilan. On verra petit à petit comment affiner ce rapport sur le fonctionnement d'OmegaT et de Windows. Ce sont des notions importantes à maitriser si vous êtes amenée à travailler tous les jours sur un ordinateur.
