### ISSUE TITLE
Travail pour le 12 mai : continuer la lecture et les propositions à partir du PDF imprimé

### ISSUE THREAD

**Issue by brandelune** [brandelune/omegat-internship#9]
Bonjour @AlexandraAnselmi57 

Je pense qu'on a finalement bouclé notre première semaine. Si on arrive à travailler comme ça sans incident technique, on bouclera le manuel ce mois-ci sans aucun problèmes.

Donc, pour aujourd'hui:
- fermer le ticket pour les tâches d'hier
- gérer les modifications prévues hier (p. 12-16)
- avancer sur la lecture, les commentaires et les modifications (p. 17-19)

**Comment by AlexandraAnselmi57** [comment]
Bilan Activité 12 mai : Correction du bilan et explications sur la récupération et l’enregistrement des modifications sur OmegaT, correction des notes de la veille, correction des notes et segments des pages 12 à 16 sur OmegaT, lecture des pages 17 à 19, prise de notes, correction des notes et segments des pages 17 à 19.

**Comment by brandelune** [comment]
J'ai validé la plupart de vos propositions, et j'ai ajouté des commentaires pour le reste.
